#!/usr/bin/env python3
"""
SGFT Stage 2 Inference.

Loads the original (un-fine-tuned) base student model and, for each test
question, uses the SG generated by the distilled student (Stage 1) as a
solution guide to produce the final answer.

Input  --sg-file:     Stage-1 output JSONL (rows have index/id, question,
                       model_response=SG, gold_ans).
Output --output-file: JSONL with {id, question, response_rationale,
                                   response_ans, answer, gold, correct}.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import List

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer


STAGE2_PROMPTS = {
    "math": (
        "Solve the following problem by following the provided solution guidelines.\n"
        "Show your reasoning and put the final numeric answer after ####.\n\n"
        "Solution Guidelines:\n{sg}\n\n"
        "Problem: {question}"
    ),
    "choice": (
        "Solve the following multiple-choice problem by following the provided solution guidelines.\n"
        "State the correct option letter as your final answer.\n\n"
        "Solution Guidelines:\n{sg}\n\n"
        "Problem: {question}"
    ),
    "text": (
        "Answer the following question by following the provided solution guidelines.\n"
        "Your final answer must be True or False.\n\n"
        "Solution Guidelines:\n{sg}\n\n"
        "Question: {question}"
    ),
}


def extract_answer(text: str, task_type: str) -> str:
    text = text.strip()
    if task_type == "math":
        m = re.search(r"####\s*(.+)", text)
        if m:
            return m.group(1).strip()
        nums = re.findall(r"-?\d+(?:[\.,]\d+)?", text)
        return nums[-1].replace(",", "") if nums else text
    elif task_type == "choice":
        matches = re.findall(r"\b([A-E])\b", text, re.IGNORECASE)
        return matches[-1].upper() if matches else text.strip()
    elif task_type == "text":
        low = text.lower()
        last_true = low.rfind("true")
        last_false = low.rfind("false")
        if last_true > last_false:
            return "True"
        if last_false > last_true:
            return "False"
        return text.strip()
    return text.strip()


def check_correct(pred: str, gold: str) -> bool:
    return pred.strip().lower() == gold.strip().lower()


def load_jsonl(path: Path) -> List[dict]:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    rows.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return rows


def load_completed_ids(path: Path) -> set:
    if not path.exists():
        return set()
    completed = set()
    for row in load_jsonl(path):
        idx = row.get("id", row.get("index", ""))
        if idx:
            completed.add(str(idx))
    return completed


def main() -> None:
    parser = argparse.ArgumentParser(
        description="SGFT Stage 2: base model generates answers using distilled-model SGs."
    )
    parser.add_argument("--base-model", required=True,
                        help="HuggingFace path of the original (un-fine-tuned) student model.")
    parser.add_argument("--tokenizer-name", default=None)
    parser.add_argument("--sg-file", type=Path, required=True,
                        help="Stage-1 JSONL output (SGs from distilled model).")
    parser.add_argument("--output-file", type=Path, required=True,
                        help="Final prediction JSONL path.")
    parser.add_argument("--task-type", default="math",
                        choices=["math", "choice", "text"],
                        help="math=GSM8K/SVAMP, choice=AQUA, text=StrategyQA.")
    parser.add_argument("--max-new-tokens", type=int, default=512)
    parser.add_argument("--max-gen-samples", type=int, default=9999)
    parser.add_argument("--max-length", type=int, default=2048)
    parser.add_argument("--bf16", action="store_true")
    args = parser.parse_args()

    tokenizer_name = args.tokenizer_name or args.base_model

    sg_rows = load_jsonl(args.sg_file)[: args.max_gen_samples]
    print(f"[Stage2] Loaded {len(sg_rows)} rows from {args.sg_file}", flush=True)

    completed = load_completed_ids(args.output_file)
    if completed:
        print(f"[Stage2] Resuming — {len(completed)} already done.", flush=True)

    dtype = torch.bfloat16 if args.bf16 else torch.float32
    print(f"[Stage2] Loading base model: {args.base_model}", flush=True)
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
        args.base_model, dtype=dtype, device_map="auto", trust_remote_code=True
    )
    model.eval()
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id

    args.output_file.parent.mkdir(parents=True, exist_ok=True)
    prompt_template = STAGE2_PROMPTS[args.task_type]

    n_correct = n_total = 0

    with args.output_file.open("a", encoding="utf-8") as out_fh:
        for i, sg_row in enumerate(sg_rows):
            idx = str(sg_row.get("index", sg_row.get("id", f"test_{i:05d}")))
            if idx in completed:
                continue

            question = sg_row.get("question", "").strip()
            sg = sg_row.get("model_response",
                            sg_row.get("response_rationale", "")).strip()
            answer_value = None
            for key in ("answer", "gold_ans", "gold", "answer_from_dataset", "ans"):
                if key in sg_row and sg_row.get(key) is not None:
                    answer_value = sg_row.get(key)
                    break
            if answer_value is None:
                answer_value = ""
            gold = str(answer_value).strip()

            if args.task_type == "choice":
                for key in ("options", "Options", "option", "Option"):
                    opts = sg_row.get(key)
                    if opts:
                        opts_text = str(opts).strip()
                        if opts_text and opts_text not in question:
                            question = f"{question}\n{opts_text}"
                        break

            prompt = prompt_template.format(sg=sg, question=question)
            messages = [{"role": "user", "content": prompt}]

            print(f"\n{'='*60}", flush=True)
            print(f"[Stage2] [{i+1}/{len(sg_rows)}] id={idx}", flush=True)
            print(f"[Stage2] PROMPT:\n{prompt}", flush=True)

            inputs = tokenizer.apply_chat_template(
                messages,
                tokenize=True,
                add_generation_prompt=True,
                return_tensors="pt",
                truncation=True,
                max_length=args.max_length,
            ).to(model.device)

            with torch.no_grad():
                output_ids = model.generate(
                    inputs,
                    max_new_tokens=args.max_new_tokens,
                    do_sample=False,
                    pad_token_id=tokenizer.pad_token_id,
                )

            response = tokenizer.decode(
                output_ids[0][inputs.shape[-1]:], skip_special_tokens=True
            ).strip()

            print(f"[Stage2] RESPONSE:\n{response}", flush=True)

            ans = extract_answer(response, args.task_type)
            correct = check_correct(ans, gold)
            n_total += 1
            if correct:
                n_correct += 1

            print(f"[Stage2] ans={ans!r}  gold={gold!r}  correct={correct}", flush=True)

            out_fh.write(json.dumps({
                "id": idx,
                "question": question,
                "response_rationale": sg,
                "response_ans": ans,
                "answer": answer_value,
                "gold": gold,
                "correct": correct,
            }, ensure_ascii=False) + "\n")
            out_fh.flush()

    acc = 100 * n_correct / n_total if n_total else 0.0
    print(f"\n[Stage2] Done. {n_correct}/{n_total} correct ({acc:.1f}%) → {args.output_file}",
          flush=True)


if __name__ == "__main__":
    main()
